spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  datasource:
    url: jdbc:h2:file:~/tododb;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver